@startuml

class Event{
}
class Conference{
}
class BoardMeeting{
}
class Member{
}
class BoardMember{
}
class Location{
}
class Person{
}
class AAUOC{
}

Conference "0..*"--"0..*" Person : attensTo
Conference --^Event
BoardMeeting --^Event
BoardMeeting "0..*"-- "0..*"BoardMember : attendsTo
BoardMember --^ Member
Event "0..*"--"1" Location : isLocatedIn
Event "0..*"--"0..*" Member : attensTo
Member --^ Person
Person "0..*"--o AAUOC
Location "0..*" --o AAUOC
Event "0..*"--o AAUOC
@enduml