@startuml

class Event{
}
class Conference{
}
class BoardMeeting{
}
class Member{
}
class BoardMember{
}
class Location{
}
class Person{
}
class AAUOC{
}

Conference -- Person
Conference --^Event
BoardMeeting --^Event
BoardMeeting -- BoardMember
BoardMember --^ Member
Event -- Location
Event -- Member
Member --^ Person
Person --o AAUOC
Location --o AAUOC
Event --o AAUOC
@enduml